{% set name = "hpo-toolkit" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 493ae3c2290dee1e48cd6f9ead71a6ba5220ef2ef5848c3b7665d90bd3b5cc57

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - hpotk
  requires:
    - tox
    - setuptools
  commands:
    - pip check
about:
  home: https://github.com/TheJacksonLaboratory/hpo-toolkit
  summary: 'Simple & Efficient Hpo Toolkit'
  license: GPL-3.0
  license_file: LICENSE
  description: |
    hpo-toolkit is a simple and efficient library for mapping loinc test results
    to hpo terms. Pure python, 3.8+

extra:
  recipe-maintainers:
    - ielis
