name: CI

on:
    push:
      branches: [ development ]
    pull_request:
      branches: [ main, development ]

jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os: [ windows-latest, macOS-latest, ubuntu-latest ]
          python: [ "3.8", "3.9", "3.10", "3.11" ]

      steps:
        - uses: actions/checkout@v2
        - name: Initialize Python ${{ matrix.python }}
          uses: actions/setup-python@v4.3.1
          with:
            python-version: ${{ matrix.python }}
        - name: Install hpo-toolkit
          run: |
            python3 -m pip install --editable .[test,docs]
        - name: Run all tests
          run: |
            pytest --co
            pytest
